version: '2'
services:
    testinterviewtask-app:
        image: testinterviewtask
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://testinterviewtask-mysql:3306/testinterviewtask?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 9292:9292
    testinterviewtask-mysql:
        extends:
            file: mysql.yml
            service: testinterviewtask-mysql
